export const DEFAULT_PERMISSIONS = [
  { code: "users.read", name: "Read users", group: "Users" },
  { code: "users.create", name: "Create users", group: "Users" },
  { code: "users.update", name: "Update users", group: "Users" },
  { code: "users.delete", name: "Delete users", group: "Users" },
  { code: "workspaces.read", name: "Read workspaces", group: "Workspaces" },
  { code: "workspaces.update", name: "Update workspaces", group: "Workspaces" },
  { code: "members.read", name: "Read members", group: "Memberships" },
  { code: "members.create", name: "Create members", group: "Memberships" },
  { code: "members.update", name: "Update members", group: "Memberships" },
  { code: "members.delete", name: "Delete members", group: "Memberships" },
  { code: "roles.read", name: "Read roles", group: "Roles" },
  { code: "roles.create", name: "Create roles", group: "Roles" },
  { code: "roles.update", name: "Update roles", group: "Roles" },
  { code: "roles.delete", name: "Delete roles", group: "Roles" },
  { code: "permissions.read", name: "Read permissions", group: "Permissions" },
  { code: "customers.manage", name: "Manage customers", group: "Customers" },
  { code: "facilities.manage", name: "Manage facilities", group: "Facilities" },
  { code: "services.manage", name: "Manage services", group: "Services" },
  { code: "contracts.manage", name: "Manage contracts", group: "Contracts" },
  { code: "operations.manage", name: "Manage operations", group: "Operations" },
  { code: "workforce.manage", name: "Manage workforce", group: "Workforce" },
  { code: "qa.manage", name: "Manage QA", group: "Quality" },
  { code: "billing.manage", name: "Manage billing", group: "Billing" },
  { code: "reports.read", name: "Read reports", group: "Reports" },
  { code: "settings.manage", name: "Manage settings", group: "Settings" },
] as const;

